### ISSUE TITLE
Add HTTPS config

### ISSUE THREAD

**Issue by brucellino** [EGI-Foundation/community.egi.eu#2]
- [x] Add the public key and signing key to the repo
  - [x] Add task to assemble the certificate chain. See [DigiCert docs](https://www.digicert.com/csr-ssl-installation/nginx-openssl.htm)
  - [x] ignore the private key
  - [x] Update group vars to use the proper config
  - [x] Redirect 80 to 443 in nginx
  - [x] Validate with ssllabs.
  - [x] Disable weak ciphers

**Comment by gwarf** [comment]
By closing the http port, you mean redirecting it transparently to 443, don't you?

**Comment by brucellino** [comment]
Actually, I had in mind to keep it closed, but now that you mention it yes, it makes sense to have the webserver redirect to https. I think a rewrite engine is needed to help deal with the headers... We definitely don't want people landing on a bare nginx page on :80 !

**Comment by brucellino** [comment]
Thanks @gwarf I updated the ticket description to better reflect what we should do.

**Comment by brucellino** [comment]
SSL Labs reports weak ciphers are enabled. I'll update the original ticket with this task
