### ISSUE TITLE
The production instance of EGI Check-In should be used

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/community.egi.eu#26]
Once possible the production instance of EGI Check-In should be used instead of the development version, to avoid potential breakage of the login flow.

**Comment by brucellino** [comment]
This is indeed in the roadmap... I guess I should sync the asana tasks with the github issues.

Thanks for reminder !

**Comment by brucellino** [comment]
Just an update - the change was made last week to the production instance of checkin
