### ISSUE TITLE
Validation email not sent when using EGI CheckIn for new account

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/community.egi.eu#9]
I've been trying to use the EGI CheckIn IdP to login, it went well but at the end (after having to specify my email that should probably have been automatically retrieved from the IdP) a validation email is sent and I never received it. I asked for a resend and it told that it was done, but nothing arrived.

**Comment by brucellino** [comment]
Thanks @gwarf Indeed I can see these errors in the log : 

`Jobs::HandledExceptionWrapper: Wrapped EOFError: end of file reached`

I'll have a look into ot.

**Comment by brucellino** [comment]
After some investigation, I found that there was a lot more communication issues talking to the service. I had followed [a topic](https://meta.discourse.org/t/running-other-websites-on-the-same-machine-as-discourse/17247) which discussed how to put discourse behind an NGINX server on the host - I guess I inadvertedly removed more in the `expose` part than I should have.

After fixing that, it seems that there is simply a problem sending mails with the relay. I don't have any feedback apart from a 402 from the server. See #8

**Comment by brucellino** [comment]
@gwarf I'm going to make a judgement call on this - the extra hassle lack of insight into what is happening is not worth using google at this point. I am going to migrate this to discourse so that we can have a civilised discussion there.

**Comment by brucellino** [comment]
This issue was moved to https://community.egi.eu/t/validation-email-not-sent-when-using-egi-checkin-for-new-account/32
